### PR TITLE
Build the CHANGELOG.md file from old tags

### PR DESCRIPTION
**Pull request by harikt**
Hi @pmjones ,

I have been thinking to release the Aura.Intl 2.x series before cake releases its next versions. 

From our earlier discussion, there was an idea of keeping CHANGELOG.md than changes.md being replaced.

The first step of creating CHANGELOG.md from older versions is done.

Eg generated for Aura.Router : 

```
# CHANGELOG 

## 3.0.1

Hygiene release: update docs, remove .gitattributes file.

## 3.0.0

First stable release.

- Default factories now use serializable method calls.

- Honor the route host and the secure flag in Generator.

## 3.0.0-beta2

First 3.x beta release.

## 3.0.0-beta1

First 3.x beta release.

## 2.3.1

Hygiene release to update docblocks.

## 2.3.0

This release adds support for a "base path" to routes. See #84, #86, and #96 for background and information. Thanks to @pine3ree and @harikt for their foundational work on this feature!

## 2.2.2

This release modifies the testing structure and updates other support files.

## 2.2.1

This is a hygiene release to update support files and documentation, with improved unit tests.

## 2.2.0

- ADD: Allow easier specification of $values['action'] directly from
  RouteCollection::add*() by passing a third param as the action value.

## 2.1.2

- DOC: Update README and docblocks.

- TST: Disable auto-resolve for container tests.


## 2.1.1

- FIX: Allow simplest possible match of a single Accept header type without a Q value.

## 2.1.0

- ADD: Router::generateRaw() to generate routes with raw data.

- TST: Add container integration tests.

## 2.0.0

First stable 2.0 release.

- DOC: Update README and docblocks.

- ADD: Methods Route::setAccept() and Route::addAccept() to match against "Accept" headers.

- ADD: Methods Route::setMethod() and Route::addMethod() to explicitly match against HTTP methods.

- ADD: Testing on Travis for PHP 5.6.

- ADD: Method Router::addHead() to add a HEAD route

- ADD: Methods Router::getFailedRoute(), Route::failedMethod(), and Route::failedAccept(), along with route match scoring, to inspect the closest non-matching route.

- REF: Various refactorings to extract complex code to separate classes

- BRK: The routes no longer add a "controller" value by default; instead, they add only an "action" value that defaults to the route name. This makes the package ADR-centric by default instead of MVC-centric.

- CHG: Use ArrayObject for value matches

- CHG: Method Router::attachResource() now adds an "OPTIONS" route.

- REF: Extract a Generator class from the Route class

- ADD: Generator::generateRaw() to use **raw** values in the route; you will need to encode them yourself.

- ADD: Method Router::getMatchedRoute() for use after matching.

- ADD: Class-based config for Aura.*_Kernel packages.

## 2.0.0-beta1

Initial 2.0 beta release.

## 1.2.0

- Add methods Map::appendMap() and Map::prependMap(), to append or prepend the definitions from another map.

- Add test for Route::__isset()

- Remove 'router_map' service from config; leave this for the framework-level config

## 1.1.1

- [DOC] Add PHP 5.5 to Travis build, update README and LICENSE.

- [ADD] Route::__isset()

- [CHG] Route::attach() now works with an empty path

## 1.1.0

- [CHG] Altered implementation of Route::generate() to encode param tokens
  using rawurlencode() instead of urlencode().

- [CHG] Altered the implementation of Route::isMatch() to decode matching
  parameters using rawurlencode().

- [CHG] In Route::generate(), use strtr() instead of str_replace() as a more
  secure mechanism

- [NEW] Specific exceptions: RouteNotFound and UnexpectedType

- [CHG] Map now throws UnexpectedType when attach route spec is bad

- [BRK] Map now throws RouteNotFound when generate() cannot find the named
  route

- [CHG] Docblock and README changes from Akihito Koriyama, Hari KT, and Stan
  Lemon

- [CHG] Map::match() now requires the $server param to be passed

- [ADD] New notation for wildcard matching; in addition to /*, we now have
  {:foo*} for optional wildcard params, and {:foo+} for required wildcard
  params. Thanks, Chris Doherty, for the report that led to this feature.

## 1.0.0

- [FIX] #14, misnamed routes. thanks kevinard.
  https://github.com/auraphp/Aura.Router/issues/14

- [ADD] Wildcard support per #15.
  https://github.com/auraphp/Aura.Router/issues/15

- [FIX] Allow for a trailing slash with no values.

- [FIX] Make it so path_prefix ending with / and path beginning with / does
  not result in double-slashes

- [CHG] Start using a Definition object

- [CHG] Allow 'attach' definitions to be callables

```

There can be special cases that we need to adjust, but it will show in long run.

Let me know if you have a different naming suggestion for commands.

Thank you

### CODE REVIEW

**Comment by pmjones** [comment]
I like it! Anything else before I merge?

**Comment by harikt** [comment]
@pmjones yes some plans.

1. When calling release make sure / grep for the version in the changelog.md .
2. Remove the changes.md file check.

I believe that's all.

Got a bit busy with something else. ie why the delay .

Sorry.

**Comment by pmjones** [comment]
@harikt , my friend, you of all people do not ever need to apologize to me for anything, *especially* not for delays :-)

**Comment by harikt** [comment]
Hi @pmjones ,

Thanks for your kind words.

I have pushed some changes, but I am not quite happy with the code. I believe it could be made better but not sure / can think of any other ways for the time being.

May be there is better regular expression to find the contents between the versions / cross verify there is a version change log present in changelog.md .

May be you have better ideas / thoughts on this and make the changes.

Thank you.

**Comment by pmjones** [comment]
> I am not quite happy with the code. 

I get that; however, it looks "good enough to start with" for me. :-)

**Pull request merged**
